### ISSUE TITLE
backpack:build does not take models in Models folder

### ISSUE THREAD

**Issue by rabol** [Laravel-Backpack/Generators#103]
The backpack:build does not look into the app/Models directory when trying to get models

### What I did:
Laravel 8 project
php artisan backpack:build

### What I expected to happen:
that the models in app/Models was processed

suggestion: an extra parameter to override the base_path() / app parameter

### What happened:
output: no models found and no CRUD's were created

### Backpack, Laravel, PHP, DB version:
backpack/crud            4.1.30 
backpack/generators v3.1.5
Laravel                         v8.22.1 
PHP                              v7.4.5

**Comment by pxpm** [comment]
@rabol `backpack:build` will search ALL models starting in `app/*` like I already told you in gitter.

If you `dd($models)` in https://github.com/Laravel-Backpack/Generators/blob/c95760bb32db50bd91b83511238288250d6dcd8b/src/Console/Commands/BuildBackpackCommand.php#L34

You should have a list of models there, including the ones inside `app/Models`. 

I don't think there is a bug here and also I think there is also an open issue to make this command interactive, so I am going to close this for now.

If you think I am wrong, and sometimes I am, please re-open.

Best,
Pedro

**Comment by StefanoBruni** [comment]
I had the same issue. The model class must contains **"extends Model"** and "**use Illuminate\Database\Eloquent\Model**" otherwise it's not recognized.

**Comment by pxpm** [comment]
Indeed @StefanoBruni, thanks for confirming, I also think that is not the proper way to handle it. 

I've already started to work on a fix for that. Generators will have some love real soon and this will be solved. I will add this note so I make sure to don't forget!

Thanks
