### ISSUE TITLE
  Class "Database\Factories\ModelFactory" not found

### ISSUE THREAD

**Issue by mansourcodes** [Laravel-Backpack/Generators#106]
# Bug report

### What I did:
after creating CurriculumCategory module I tried to seed it.
`php artisan db:seed --class=CurriculumCategorySeeder`

### What I expected to happen:

seeding the database

### What happened:

```

   Error 

  Class "Database\Factories\CurriculumCategoryFactory" not found

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:680
    676▕     public static function factoryForModel(string $modelName)
    677▕     {
    678▕         $factory = static::resolveFactoryName($modelName);
    679▕ 
  ➜ 680▕         return $factory::new();
    681▕     }
    682▕ 
    683▕     /**
    684▕      * Specify the callback that should be invoked to guess factory names based on dynamic relationship names.

      +1 vendor frames 
  2   database/seeders/CurriculumCategorySeeder.php:17
      App\Models\CurriculumCategory::factory()

      +22 vendor frames 
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

### What I've already tried to fix:

the problem because the factory class are located in a subfolder 

### Backpack, Laravel 8, PHP 8:
Laravel 8, PHP 8

**Comment by mansourcodes** [comment]
The default location for CurriculumCategoryFactory is `database/factories/Models/CurriculumCategoryFactory.php`
when I moved it to `database/factories/CurriculumCategoryFactory.php` **it worked**

**Comment by promatik** [comment]
Hi @mansourcodes can you provide all the commands you've executed?
Because backpack doesn't deal with the Model factory.

When you run `php artisan backpack:crud Test`
This will create the Model, Controller, and Request, not the factory ...

**Comment by mansourcodes** [comment]
actually I need factory

**Comment by tabacitu** [comment]
@mansourcodes take note that [Laravel 8 uses different factories by default](https://laravel.com/docs/8.x/upgrade#model-factories). That might be your problem.

I'm pretty sure this has nothing to do with Backpack - at the moment Backpack does not generate factories, does not touch your factories, does not use your factories. So it sounds like it's a Laravel issue you're having, not a Backpack issue.

Let us know if I'm wrong, and we'll reopen 😉 It's been known to happen 😂

PS. However, we _are_ working on a way to generate better models AND factories in the next version. Subscribe to our newsletter to find out when it's out - I'm super excited about it.

**Comment by saberfazliahmadi** [comment]
Ran into this issue when trying to use a factory in a package. I solved it by overriding the HasFactory::newFactory() method.

class LegacyCategory extends Model
{
    use HasFactory;

    ...    

    /**
     * Create a new factory instance for the model.
     *
     * @return \Illuminate\Database\Eloquent\Factories\Factory
     */
    protected static function newFactory()
    {
        return new LegacyCategoryFactory();
    }			
}

**Comment by zfm-andreasmatuszewski** [comment]
> The default location for CurriculumCategoryFactory is `database/factories/Models/CurriculumCategoryFactory.php` when I moved it to `database/factories/CurriculumCategoryFactory.php` **it worked**

If you have subfolders in the factories folder you have to add these in your `composer.json`:
```
...
"autoload": {
        "psr-4": {
            ...
            "Database\\Factories\\Models\\": "database/factories/Models/",
            ...
        }
}
...
```
