### ISSUE TITLE
BadMethodCallException : Method Illuminate\Support\Str::of does not exist. while running php artisan backpack::crud

### ISSUE THREAD

**Issue by salmanaligeek** [Laravel-Backpack/Generators#115]
# Bug report

### What I did:
`php artisan backpack::crud Test`
or
`php artisan backpack:crud-controller Test `

### What I expected to happen:
New backpack CRUD controller

### What happened:
```
    BadMethodCallException  : Method Illuminate\Support\Str::of does not exist.

  at /home/salman/Work/FixingBug/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:77
    73|      */
    74|     public static function __callStatic($method, $parameters)
    75|     {
    76|         if (! static::hasMacro($method)) {
  > 77|             throw new BadMethodCallException(sprintf(
    78|                 'Method %s::%s does not exist.', static::class, $method
    79|             ));
    80|         }
    81| 

  Exception trace:

  1   Illuminate\Support\Str::__callStatic("of")
      /home/salman/Work/FixingBug/vendor/backpack/generators/src/Console/Commands/CrudBackpackCommand.php:31

  2   Backpack\Generators\Console\Commands\CrudBackpackCommand::handle()
      /home/salman/Work/FixingBug/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
```

### Backpack, Laravel, PHP, DB version:
Laravel 6.20.30, PHP 7.3, MariaDB 10.3.29

**Comment by pxpm** [comment]
ping @tabacitu 

`Str::of` does not exist in Laravel 6. 

I think an easy fix is to add a macro in case it doesn't exist:

```php
//GeneratorsServiceProvider.php

//check if method `of` exists in Str class, if not register it

Str::macro('of', function (..) {
// replicate laravel code for `of` function
})
```

What do you think ?

Best,
Pedro

**Comment by tabacitu** [comment]
Ouch! Yeah we probably forgot we support L6 too... sorry @salmanaligeek ! 

Seems like this has happened in this commit https://github.com/Laravel-Backpack/Generators/commit/8597e4eed25d7b8d5fd8c07ef0cb9ed3ac37eb44 - when @promatik fixed stuff, he also started using the Fluent Helpers. I didn't notice it in my review, sorry. It would have been fine if we dropped support for L6 right then and there, but now that we have tagged versions with L6 support and `Str::of()`... we're forced to fix it and keep L6 support.

I don't think adding a Macro would be an easy way out... I expect it's not as easy as that to add Fluent Strings to L6.

I think our best bet is to rewrite those bits to no longer use the Fluent String Helpers, but normal String Helpers. Even though the code would be uglier, it'll support L6-L8 and fix the problem.

**Comment by pxpm** [comment]
@tabacitu 

I've just had a grip on this, and the macro part is just that easy:

```php
// notice `off` because I am in a version where `of` is available
if(class_exists('\Illuminate\Support\Str') && !method_exists('\Illuminate\Support\Str', 'off')) {  
            \Illuminate\Support\Str::macro('off', function($string) {
                return new \Illuminate\Support\Stringable($string);
            });
        }
```

Problem is that in L6 there is no `\Illuminate\Support\Stringable` class. So yeah, in this specific scenario is better to just write with other Str functions, otherwise the macro would be just fine! :)

I will assign myself to this and fix it.

Thanks,
Pedro

**Comment by promatik** [comment]
My bad, sorry 🙃

@pxpm I did the mess, I fix it 😅 the PR is here; https://github.com/Laravel-Backpack/Generators/pull/116

```php
$nameTitle = Str::of($name)->afterLast('\\');
$nameKebab = $nameTitle->kebab();
$nameSingular = $nameKebab->replace('-', ' ');
$namePlural = $nameSingular->plural();
```

This was so beautiful 🤷‍♂️

**Comment by tabacitu** [comment]
Strong columns are the best!

![angry-power-gif-by-spongebob-squarepants](https://user-images.githubusercontent.com/1032474/203592229-76bcfa34-b18d-4f53-9637-e28fa6add03b.gif)

**Comment by Keanhor2** [comment]
Hello brother ! again I have a problem when I try to compile vue js in laravel :


webpack compiled successfully
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources/sass'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources/js/components'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/public'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources/js/components'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/public'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources/sass'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/public'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/public'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/public'
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/cguser/Personal project/khmer_food/resources'

**Comment by tabacitu** [comment]
Sorry @Keanhor2 that has nothing to do with this thread. If you think it's Backpack-related, open a different issue. But it looks to me like it's got nothing to do with Backpack, but VueJS/Laravel. Cheers!

**Comment by Keanhor2** [comment]
Hello all be loved brother ! Can you help to solve this problem :
1. here is my script : For this I uesd laravel and vue js.
<script>
export default {
    data(){
        return{
            method:false,
            customers:{},
            form: new Form({
                id:'',
                name:'',
                gender:'1',
                phone:'',
                address:'',
                _token:this.token.value
            }),
        }
    },
 
    methods: {
        newCustomer(show){
             this.from.reset();
            $('#modal-customer').modal('show');
        },
</script>

//=========================problem =============================
1, ![image](https://user-images.githubusercontent.com/90302802/204845768-232f3a35-ce5c-4cb3-8c2d-7edafa0dbd97.png)

2, 
![image](https://user-images.githubusercontent.com/90302802/204846636-e30561d9-893f-46f2-883a-0cfe2819638c.png)

**Comment by tabacitu** [comment]
@Keanhor2 no. Please stop posting non-Backpack issues here - this is spam. This is your second warning - third time you'll get banned.
