### ISSUE TITLE
[Bug]  Installation of backpack/generators with backpack/crud:"4.2.*" fails on new laravel project.

### ISSUE THREAD

**Issue by PitchRE** [Laravel-Backpack/Generators#124]
# Bug report

### What I did

Created fresh laravel project.
Executed 
```
composer require backpack/crud:"4.2.*"
composer require --dev backpack/generators
```

### What I expected to happen
Package being installed succesfully.

### What happened

Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - backpack/base[dev-master, 1.1.9, ..., 1.1.13] require laravel/framework 5.8.*|^6.0 -> found laravel/framework[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8.65).
    - backpack/base[0.9.0, ..., 0.9.7] require laravel/framework 5.5.*|5.6.* -> found laravel/framework[v5.5.0, ..., 5.6.x-dev] but it conflicts with your root composer.json require (^8.65).
    - backpack/base[0.9.8, ..., 0.9.12] require laravel/framework 5.5.*|5.6.*|5.7.* -> found laravel/framework[v5.5.0, ..., 5.7.x-dev] but it conflicts with your root composer.json require (^8.65).
    - backpack/base[1.0.0, ..., 1.0.4] require laravel/framework 5.6.*|5.7.* -> found laravel/framework[v5.6.0, ..., 5.7.x-dev] but it conflicts with your root composer.json require (^8.65).
    - backpack/base[1.1.1, ..., 1.1.8] require laravel/framework 5.8.* -> found laravel/framework[v5.8.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8.65).
    - backpack/generators[v3.1.0, ..., v3.1.11] require backpack/crud 4.1.* -> found backpack/crud[4.1.0, ..., 4.1.x-dev] but it conflicts with your root composer.json require (4.2.*).
    - backpack/generators v3.x-dev requires backpack/base 0.9.*|1.0.*|1.1.* -> satisfiable by backpack/base[0.9.0, ..., 0.9.12, 1.0.0, ..., 1.1.13].
    - backpack/base 1.0.x-dev is an alias of backpack/base dev-master and thus requires it to be installed too.
    - Root composer.json requires backpack/generators ^3.1 -> satisfiable by backpack/generators[v3.1.0, ..., v3.x-dev].

```
     

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
PHP 8.0.13 (cli) (built: Nov 22 2021 09:50:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.76.2@c67acfdc968f487b6235435080eef62a7e2ed055

### BACKPACK VERSION:
4.2.x-dev@7c34334db53c2ddd03f958369b7294615345b562
```

**Comment by tabacitu** [comment]
@PitchRE , heads-up: I'm pretty sure none of the Backpack addons will get 4.2 support until we actually launch 4.2. Until then, if you want to use 4.2-dev, it's recommended you do `composer require backpack/crud:"4.2.x-dev as 4.1.99`

That should make all of them install just fine, as if you were running 4.1.x

**Comment by PitchRE** [comment]
@tabacitu Thank you. I am now able to play with it.
I just got confused by the docs and expected it to work.

@pxpm 
https://github.com/Laravel-Backpack/CRUD/pull/4002
Thank you for this PR. Its amazing, I was waiting for it!

**Comment by pxpm** [comment]
Yeah, sorry didn't come to mind installing dev-branch as 4.1. 

It's a fast moving branch, so make sure you pull the updates regularly. 

There are some known issues I am gathering here: https://github.com/Laravel-Backpack/CRUD/issues/4012

Let me know if you spot something else that I missed. 

Thanks,
Pedro

**Comment by tabacitu** [comment]
My bad - the docs did not mention this. I've just updated the 4.2 docs to instruct people to use `4.2.x-dev as 4.1.99` for now.
