### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/Generators#125]
# Bug report

### What I did

php artisan backpack:crud page

### What I expected to happen

generate 

`<li class="nav-item"><a class="nav-link" href="{{ backpack_url('page') }}"><i class="nav-icon la la-question"></i> Pages</a></li>`

in `sidebar_content.blade.php`

### What happened

generated 

`<li class='nav-item'><a class='nav-link' href='{{ backpack_url('page') }}'><i class='nav-icon la la-question'></i> Pages</a></li>
`
Note the nested single quotes.

This is not compatible with my pretty printer, it breaks the code by inserting a space 
`href='{{ backpack_url(' page') }}'`

This is also not consistent with the other `sidebar_content.blade.php` code provided by backpack.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:40) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.77.1@994dbac5c6da856c77c81a411cff5b7d31519ca8

### BACKPACK VERSION:
4.1.62@273c277e826c157ef0913962769a7ec9a44b6233

**Comment by pxpm** [comment]
Hey @Polfo 

Thanks for the report.I know it works, but it was weird indeed to have single quotes on the html elements.

I've just submitted PR #126 that should address this issue. 

I am going to close this, if you happen to give that PR a try let us know if it fixed for you. 

Merry Christmas,
Pedro

**Comment by tabacitu** [comment]
Heads-up @Polfo , we're currently very _very_ deep into finishing the 4.2 launch. So you might get late answers from us on Github, when issues are minor. Let me be clear - _minor issues like these are still important_. They add up, and having them fixed makes up for a MUCH better developer experience. We really appreciate you submitting them, and want you to keep doing that.

But **in the next few weeks, we might not answer to minor issues at all (or answer late)**. Please know that we saw them... we'll take care of them... but we won't spend time on them right away. Not until we're done launching 4.2. 

That is the priority numero uno for us - the 4.2 launch. Afterwards, we can take care of these "quality of life" improvements.

Thanks again for helping out.
Cheers!
