### ISSUE TITLE
[improvement] refactor the way we validate that file is a model

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/Generators#132]
at the moment we check if the string `use Illuminate\Database\Eloquent\Model` and `extends Model`. If you use `extends \lluminate\Database\Eloquent\Model` it would not be detected as a model.

**Comment by tabacitu** [comment]
I think this would be an easy fix for https://github.com/Laravel-Backpack/Generators/issues/105

**Comment by promatik** [comment]
Oh wait ...
This is fixed here #146

BUT, #105 is a different issue 😅

@tabacitu I'll close this one because this is exactly what #146 aims 👌
If I'm wrong, please revert.
