### ISSUE TITLE
Create a `php artisan backpack:button` command

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#135]
# Bug report

### What I did:

Created an operation, had no way to create a custom button really quick (with a stub).

### What happened:

Run `php artisan backpack:button email` and it would create the button for me.

### What I've already tried to fix it:

Asked @karandatwani92 to do it 😅👀

**Comment by karandatwani92** [comment]
Aye Aye! captain :D

**Comment by karandatwani92** [comment]
PR #141

**Comment by tabacitu** [comment]
Whoohooo 🎉 Let's close this in favor of #141 then, we'll continue the conversation there.
