### ISSUE TITLE
Add optional flags to `php artisan backpack:crud`

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#137]
# Bug report

### What I did:

```
php artisan backpack:crud user
```

### What I expected to happen:

Generate a CrudController, route, sidebar item.

### What happened:

Generates a CrudController, route, sidebar item, Request.

But then, since I want to use the field validation, I have to go delete the Request file, and its mention in the CrudController...

How about we start creating flags on the `backpack:crud` command? Maybe:
- (MUST) `--no-request` will not create the Request? alternatively, maybe we do `--validation=request/array/field` and it populates the CrudController with example code for each? this second option would make it easier for us to convert this into a question later on (or starting now, really), the question would be "_How would you like to enter your validation rules for the Create and Update Operations?_" and the dev could choose between them;
- (SHOULD/COULD) `--syntax=fluent` or `--syntax=array` - would fix #89 but... should we? or should we just nudge people towards using the fluent syntax?
- (COULD/WON'T) `--operations=list,create,update,delete,show` to choose which operations it would have? I think this is overkill to be honest... 99% of all CRUDs will need all of them, and it's super-easy to remove them in the CrudController soo... yeah, let's not do this;

Questions here:
- (1) What else? What else do devs _often_ need to customize, on the generated CrudController?
- (2) Which ones of the above do we actually do? I say `--validation` first, then maybe `--syntax`;

**Comment by tabacitu** [comment]
@promatik what do you think?

For context, I've run into this problem when following our new "Getting Started" instructions:
<img width="941" alt="CleanShot 2022-08-17 at 09 51 39@2x" src="https://user-images.githubusercontent.com/1032474/185053745-622566ca-5860-4c8d-99b7-975b1c1fbc7b.png">

This could be simplified, if the `php artisan backpack:crud User` command would either ASK which type of validation I want, or add no validation by default... Right now, since we have [3 types of validation](https://backpackforlaravel.com/docs/5.x/crud-operation-create#validation-1) it feels a bit odd for the default to be the most complex one...

Either way, I'd really _really_ like us to have a solution, to simplify the steps above. People shouldn't have to delete files when following our very first instructions...

**Comment by tabacitu** [comment]
I've tagged this MUST because of the `--no-request` or `--validation=array` flag, which I do think is a MUST. The rest... we can figure out later.

**Comment by promatik** [comment]
PR for this one https://github.com/Laravel-Backpack/Generators/pull/143 🙌

**Comment by tabacitu** [comment]
Closed by https://github.com/Laravel-Backpack/Generators/pull/143
