### ISSUE TITLE
Command to create a new page:

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#138]
`php artisan backpack:page`

By that I mean a custom page, like a Dashboard or something. Currently we don't even have INSTRUCTIONS for this, no documentation, nothing, it's crazy.

Yes, it's a simple thing to do if you understand how Backpack works. But it's NOT so simple if you don't. And it's a perfect way to introduce people to how Backpack works. Run `php artisan backpack:page status` and it will create:
- a GET route in `routes/backpack/custom.php`
- a controller in `app/Http/Controllers/Admin/StatusController.php` with one method, `status()`, loading one view
- a view in `resources/views/vendor/backpack/crud/pages` (?!?!) or where would be a good place for this?

That should make it dead-simple for someone to create custom pages, right? And it would make it easy for us to:
- add docs about how to do this
- use this process inside a Getting Started video, maybe even as a pre-cursor to creating a CRUD (because it's simpler)

**Comment by pxpm** [comment]
You are creating application views (your own) don't use `/vendor` I guess.

base: `resources/views/`

`php artisan backpack:page status` => `resources/views/status.blade.php`
`php artisan backpack:page app.dashboard` => `resources/views/app/dashboard.blade.php`

noice to have:
`php artisan backpack:page app.dashboard --layout"top-left/blank"` =>Would create a view extending one of the backpack layouts.

**Comment by promatik** [comment]
@tabacitu @pxpm should we add sample content on this created page?

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/1838187/185910458-a82cf595-1edc-4202-b918-2d1e4708a634.png">

**Comment by pxpm** [comment]
I think the info where the view is located etc should be there, I agree. 
Plus points if we have the "editor" from dev and he could just click and open the file in the editor. (it's a COULD i guess, not mandatory, but a nice to have 🙃 )

**Comment by promatik** [comment]
I agree @pxpm, since that's on DevTools, we will provide it if the user has DevTools, otherwise, we don't 🤷‍♂️

**Comment by tabacitu** [comment]
Awesome! Yes, totally, clickable would be great.

I'm still torn on view location... 
- I don't like directly in resources/views, because that's where main all views go. 
- I don't like in resources/views/vendor either because (1) it's in vendor and (2) it doesn't make sense in "base" nor in "crud"

I guess in "resources/views/admin"? But that would be unlike anything we have right now...

**Comment by promatik** [comment]
@tabacitu we could leave that decision for the developer, but we could teach and document the usage of the admin prefix.

I was doing that myself to test;

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1838187/185935370-a2c61fbc-86ca-4293-9b47-af602fe00456.png">

In the documentation we use `admin.status` or `admin/status`, both work. Developers will understand that if they want the main views folder, they just remove that prefix.

**Comment by tabacitu** [comment]
Hmmm... I don't know if it's 100% intuitive... you remove the "admin prefix" and the view is no longer in "resources/views/admin", but... the controller is still in "app/Http/Controllers/Admin", isn't it?...

**Comment by promatik** [comment]
Yes, it's true. 
Anyway I don't think we should go and match Controller and View locations ...

What should we do?
I would opt for this non 100% intuitive solution, but as an alternative, I would force everything to be inside `admin` » `resources/views/admin`.

**Comment by pxpm** [comment]
> Awesome! Yes, totally, clickable would be great.
> 
> I'm still torn on view location...
> 
> * I don't like directly in resources/views, because that's where main all views go.
> * I don't like in resources/views/vendor either because (1) it's in vendor and (2) it doesn't make sense in "base" nor in "crud"
> 
> I guess in "resources/views/admin"? But that would be unlike anything we have right now...

The only thing preventing you from using `resources/views` is your "mental usage" for the application organization I guess, so you @tabacitu would store the admin views inside `admin/`, I would store in `backend`, so why are we thinking that adding the prefix (admin, vendor, backpack wtv) is intuitive in any way??
The `application view folder` is `resources/views` if I want all my views on the base folder, why not ? Maybe I want to create a page that is not for "admin" but it's for "manager" and I am using `rss/admin` and `rss/manager` to organize my views.

I have the same feeling about Controllers, the application base is: `app/Http/Controllers`, and it should create the controller with the same prefix that I defined when creating the view.

A small workaround would be `--folder/prefix="mycustom.folder.structure"` and by default would be `admin` ... With a config to make it global configurable (imagine that I want to replace `admin` for `backend` in all the pages I generate).

And also --controller="custom.folder", that by default would be the same as the view if `--controller` is not provided. 

I would be happy with this solution too, and we would not be telling people how they should structure their app, but we provide sensible defaults.

**Comment by promatik** [comment]
@pxpm I mostly - 99% - agree 👌
I just fear we are complicating this too much 😅

IMO we have two solutions;
1) KISS — Keep it super simple, Controller goes on `Admin` folder, view goes on `resources/views` and the developer can set the full path by doing `php artisan backpack:page admin.status.monster`
2) (@pxpm suggestion above) Accept multiple arguments for both controller and view, something like;
`php artisan backpack:page status --controller=admin --view=admin --layout=blank` — both defaults to admin.

I'm tending to 2).

@pxpm let correct me if I said something wrong, @tabacitu let us know if you have a 3rd option ✌️

**Comment by tabacitu** [comment]
Ok so... no matter what we do, we're introducing an inconsistency here. The decision then becomes, _which inconsistency is less bad?_ And I think this one is the least bad: **we create them in `resources/views/admin`.** Just like you can't configure a CrudController to be generated outside the `admin` namespace, you can't configure the view to be generated outside `admin` either.

We can add that later, using a `--flag` or an interactive question-and-answer system. But that's a SHOULD/COULD, not a MUST, so it's not for now. Until then, if you want it outside the `admin` directory, move it outside the admin directory manually. I think that's reasonable.

This sets a good precedent and encourages the following structure:
- `resources/views` - app views
- `resources/views/admin` - custom admin views
- `resources/views/vendor/backpack/crud` (&base) - package overrides and custom fields

I think that's easy to understand. The consistency I've chosen here is between the generated Controller and the generated view. And to nudge people into following a simple file structure for views, just like we've _successfully_ done with the Controllers (and most people have followed) and like we _should have_ with the Requests (and I regret we haven't done).

Sounds reasonable?

**Comment by promatik** [comment]
https://github.com/Laravel-Backpack/Generators/pull/140 🙌
