### ISSUE TITLE
Method Illuminate\Support\Stringable::lcfirst does not exist.

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/Generators#148]
# Bug report

### What I did

I enter the command

 php artisan backpack:crud subscription

I get in response:

   INFO  Creating CRUD for the Subscription model:

   BadMethodCallException

  Method Illuminate\Support\Stringable::lcfirst does not exist.

  at D:\laragon\www\storry\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕

  • Bad Method Call: Did you mean Illuminate\Support\Stringable::ucfirst() ?

  1   D:\laragon\www\storry\vendor\backpack\generators\src\Console\Commands\CrudModelBackpackCommand.php:59
      Illuminate\Support\Stringable::__call("lcfirst", [])

  2   D:\laragon\www\storry\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Backpack\Generators\Console\Commands\CrudModelBackpackCommand::handle()

### What I expected to happen

Added crud.

### What happened

Got an error Method Illuminate\Support\Stringable::lcfirst does not exist.

### What I've already tried to fix it

I don't know what to do

### Is it a bug in the latest version of Backpack?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.23@bdc707f8b9bcad289b24cd182d98ec7480ac4491

### BACKPACK VERSION:
5.3.12@883ff76f74bb4cdb70559990026b1130db5234f6

**Comment by pxpm** [comment]
fixed in #149

**Comment by tabacitu** [comment]
Merged & tagged. Thank youuu 🙏
