### ISSUE TITLE
[bug] generating nested controllers and models

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/Generators#169]
If I write in small letters:

`php artisan backpack:crud post/badge`

Creates classes with small letters (badgeCrudController).

If I write in capital letters:

`php artisan backpack:crud Post/Badge`

Cannot add CrudTrait to model. And an error occurs:

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Http\Controllers\Admin\Post/BadgeCrudController] does not exist.
```

Because of the slash in the 'Post/BadgeCrudController' routes. 

Also, does not find the model in the controller due to the wrong namespace.

`CRUD::setModel(\App\Models\Badge::class);`

Although the model is located here \App\Models\Post\Badge::class

Now I checked it - it does not display entries for models in folders, it gives a 404 error.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.25@b77b908a9426efa41d6286a2ef4c3adbf5398ca1

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

**Comment by pxpm** [comment]
Thanks for the report @AlexKomMsk 

I've moved this to the appropriate repository. 

From a quick test this is what I got:

![image](https://user-images.githubusercontent.com/7188159/205276575-b417076f-5314-4019-9ff3-4d82c8d8d1bc.png)

I reproduced the issues mentioned. This may require some fixes in generators.

I will postpone this to work on it next week.

**Comment by tabacitu** [comment]
I'd assign this to @maurohmartinez - I think it would be a good introduction to this repo, which needs a little bit more attention. Normally this is Antonio's baby, but I don't want to distract him from working on v6.

**Comment by maurohmartinez** [comment]
Closing and moving this to [PR](https://github.com/Laravel-Backpack/Generators/pull/171).
