### ISSUE TITLE
PHP 8.2 deprecation warning in PageBackpackCommand

### ISSUE THREAD

**Issue by mattsches** [Laravel-Backpack/Generators#178]
# Bug report

Testing my application on PHP 8.2.0, I get a deprecation warning:

```
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/backpack/generators/src/Console/Commands/PageBackpackCommand.php on line 73
```

### What I did:
I switched to PHP 8.2 and ran the PHPUnit tests for my application.

### What I expected to happen:
Get no deprecation warnings.

### What happened:
`Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/backpack/generators/src/Console/Commands/PageBackpackCommand.php on line 73`

### What I've already tried to fix it:
It's a simple fix and I will provide a PR :)

### Backpack, Laravel, PHP, DB version:
```shell
$php artisan backpack:version
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/backpack/generators/src/Console/Commands/PageBackpackCommand.php on line 73
### PHP VERSION:
PHP 8.2.0 (cli) (built: Dec  8 2022 15:03:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.0@eb85cd9d72e5bfa54b4d0d9040786f26d6184a9e

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 4.1.66
backpack/permissionmanager: 6.0.11
backpack/generators: v3.1.13
```

**Comment by pxpm** [comment]
Thanks again @mattsches 

Let's close this in favor of the PR 🙏
