### ISSUE TITLE
3.3.16 Method Illuminate\Support\Stringable::value does not exist on `php artisan backpack:build`

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#196]
backpack/crud: 5.6.1
backpack/editable-columns: 2.1.5
backpack/generators: 3.3.16
backpack/pro: 1.6.6

php artisan backpack:build

BadMethodCallException
Method Illuminate\Support\Stringable::value does not exist.
  at \vendor\laravel\framework\src\Il
luminate\Macroable\Traits\Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕
  1  \vendor\backpack\generators\src
\Console\Commands\BuildBackpackCommand.php:86
      Illuminate\Support\Stringable::__call("value", [])

  2 \vendor\backpack\generators\src
\Console\Commands\BuildBackpackCommand.php:66
      Backpack\Generators\Console\Commands\BuildBackpackCommand::getModels...

_Originally posted by @blessen131 in https://github.com/Laravel-Backpack/Generators/issues/185#issuecomment-1636108692_

**Comment by tabacitu** [comment]
@blessen131 please keep in mind that we've already launched Backpack v6, and that does not have this bug. If you're starting a new project, I heavily recommend you use v6.

I will ask @pxpm to take a quick look at this nonetheless, and if it's an easy fix, fix it. But officially we are no longer pushing bug fixes to Backpack v5, only security fixes - https://github.com/Laravel-Backpack/CRUD/blob/main/SECURITY.md

**Comment by blessen131** [comment]
I updated, $namespace = (string)$fileContent->match('/namespace (.*);/'); & 
 $classname = (string)$fileContent->match('/class (\w+)/');  in 'vendor/backpack/generators/src/Console/Commands/BuildBackpackCommand.php' that fix my error/issue

**Comment by tabacitu** [comment]
Fixed in #198  - a `composer update` should fix it for you @blessen131 . Let us know if that's not the case and we'll reopen. Cheers!
