### ISSUE TITLE
Suggestion: use PHP-parser library for code generation

### ISSUE THREAD

**Issue by uniconstructor** [Laravel-Backpack/Generators#27]
Hello everyone.

I have a proposition about Backpack CRUD generators implementation.
Instead of using ".stub" files and template-based file generation you can use a PHP-parser project for generate class abstract syntax tree: https://github.com/nikic/PHP-Parser/blob/master/doc/4_Code_generation.markdown

I think this is a definitely better way for code generation, because of several reasons:
- PHP-parser more configurable - you can add any number of additional arguments as you want
- you will not generate code that you don't need (no more commented parts of code that are usually deleted after generation)
- you can configure code style of generated code (currently code in all generated classes differs from my project codestyle and I have to reformat them)
- you can add support of external Laravel plugins much easier  (I use [Eloquence](https://github.com/jarektkaczyk/eloquence) for all my models, and I need to add all traits and options to every generated model manually)
- you will never have a syntax errors in code generated from abstract syntax tree
- AST generator can rely on table/model structure, CLI user input or Backpack configuration files and will always represent actual project structure
- docblock-comments can also be generated via AST
- you can even modify existing (already generated) classes instead of manually rewriting code. Think of it as of some kind of automated refactoring operation
- and finally, code generation is not like text or markup generation - so we need to use a different approach for this task

Backpack generators have not very large codebase now, and I think this is not too late to switch form template-based generation to AST-based generation.

I like Backpack project and I think it deserves a really good code generation support.
Any feedback or discussion are welcome.

**Comment by tabacitu** [comment]
Hi @uniconstructor ,

I do agree this looks like a more comprehensive tool for generating PHP code. We're planning on improving the generators a lot in the coming months, so thank you for the package and your thoughts, will take into consideration.

That being said, I'm not 100% sure it's the best tool for our needs:
- looks a bit complicated for the little things we need to do;
- recently our efforts have been to _eliminate_ dependencies, not add new ones;
- if we _do_ decide for a new dependency, we _could_ go for a more Laravelly package, that generates a model from a migration, or something like that;

That being said, my mind's not made up yet. Please pitch in with your thoughts. Others are invited to do the same.

Thanks, cheers!
