### ISSUE TITLE
Permission on field.

### ISSUE THREAD

**Issue by cerelli** [Laravel-Backpack/Generators#28]
Hi, I wanted to know how I can set permissions on fields.
I have the account model with field1, field2, field3 and field4.
I want to set that user A can see field1, field2 but can not change field3 and field4 does not see it right.
It would be possible ?

Thanks.

**Comment by lloy0076** [comment]
@cerelli - this cannot be set from within the generator **and** this is the wrong package to ask this question.

@cerelli - the question you ask is almost as broad as asking how to use authentication in Laravel; you'd need to decide what you're using for your controller(s) -- i.e. plain Laravel controllers, Backpack/CrudControllers or something else -- and then ask **in the appropriate** place.

Honestly, I'd ask this question in our gitter community and if you're going to use the Backpack/CrudController (quite likely) then please ask in that place (https://github.com/Laravel-Backpack/CRUD).
