### ISSUE TITLE
Missing $request parameter

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/Generators#29]
When manipulation the `$request` in the `store`or `update` methods of a `CrudController` and you don't inject it to the parent methods, your manipulations are not present.

As this happens to me far too many times (and there was currently a question in Gitter) I would suggest add the `$request` paramter to the `parent::storeCrud()` call and `parent::updateCrud()`call in the Controller template.

Currently this looks like:

```php
    public function store(StoreRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::storeCrud();
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }

    public function update(UpdateRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::updateCrud();
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }
```

and would be changed to

```php
    public function store(StoreRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::storeCrud($request); // inject the request instance
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }

    public function update(UpdateRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::updateCrud($request); // inject the request instance
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }
```

**Comment by lloy0076** [comment]
This is highly unlikely to apple cart someone unless they were doing something entirely unexpected (but what, I'm not sure).

I'll mark as an enhancement for want of a better label.

**Comment by OliverZiegler** [comment]
As this only affects the generation of the template files, i don't think there should be any problems with that. Created the PR

**Comment by tabacitu** [comment]
Totally agree - not a breaking change, as it only relates to controllers you generate from now on. I've also been by this, great to finally see it fixed. 

Thanks a lot, merging the PR now!

Cheers! Keep 'em coming.
