### ISSUE TITLE
Allow stubs to be taken from a different location

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/Generators#32]
Hi,

I'd like to be able to use my own stubs -- obviously based on the ones you already have. It makes sense to update `getStub` so that it checks either if stubs are stored in a different location, or accept an argument allowing you to pass a directory where the stubs are located.

Thanks.

**Comment by tabacitu** [comment]
Hi @niladam ,

I think this would be a good feature. I think the cleanest implementation would be to overwrite them just like config files - if a file with the same name exists in a directory, it will pick that one up. If not, it will pick up the one in the package.

The question now is - what would be a good place to store custom stubs? :-) ```stubs/vendor/backpack/generators``` maybe? This would also leave room for other pacakges to do the same, it will make sure no one stub is used for multiple packages, and you'd be able to re-use stubs across multiple namespaces, in case you have one Laravel installation with multiple apps. But it would add another folder to the root directory. I know some people don't like that.

What do you think?

Cheers!

**Comment by niladam** [comment]
hey @tabacitu; Personally, i've used WordPress more in the past few years and i've come to love WordPress' [locate_template](https://core.trac.wordpress.org/browser/tags/4.9.2/src/wp-includes/template.php#L629) function. 

Basically, what the function does is it searches for a specific file with the following priority:

STYLESHEETPATH/file_name (ie: where the style.css is located)
TEMPLATEPATH/file_name (ie: root of the current theme);
ABSPATH . WPINC . '/theme-compat/' (a hard-coded folder named theme-compat in the wp-includes folder -- this is generated based on WPINC);

I think this is a really powerful idea. Because it basically allows you to have 3 path locations. One of theme can be just the root of the layout; 

Since WordPress uses a child-theme approach that's what the TEMPLATEPATH is for. That's basically the main layout's folder. STYLESHEETPATH is the child-theme path;

I think i'll leave this to you, but i think providing a number of 2-3 options where the user can place his own would be a great feature.

**Comment by niladam** [comment]
@tabacitu i think this should be looked into :)

**Comment by tabacitu** [comment]
Up! Really now, Justin... :-)

**Comment by tabacitu** [comment]
Up! :-)
