### ISSUE TITLE
Wrong namespace of generated classes

### ISSUE THREAD

**Issue by adrianmiu** [Laravel-Backpack/Generators#35]
# Bug report
The generated files do not take the app name into account for the Request classes in the `use ` lines in the Controller

### What I did:
Generated the crud for a model

### What I expected to happen:
The crud to work as expected

### What happened:
Exception: Class App\Http\Requests\xxxRequest does not exist

### Backpack, Laravel, PHP, DB version:
backpack/generators: 1.1.11

**Comment by adrianmiu** [comment]
Problem is in crud-controller.stub

```
use App\Http\Requests\DummyClassRequest as StoreRequest;
use App\Http\Requests\DummyClassRequest as UpdateRequest;
```

**Comment by tabacitu** [comment]
Thank you @adrianmiu ,

You're right, Generators doesn't support custom namespaces right now. It should. Let's leave this open until we get this fixed.

Thanks, cheers!

**Comment by tabacitu** [comment]
Still a thing. Should be fixed.
