### ISSUE TITLE
Merge Generators into Base

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#4]
For simplicity, I think backpack/base should include all generators functionality.
It's never been used outside it anyway. 

OR

We should require it and install it by default with backpack/base, once the installer is ready.
But that might take some time.

I vote include it in Base. @cristiantone , what say you?

**Comment by tabacitu** [comment]
On second thought, maybe Generators should only be available in the development environment... just like [laracasts/generators](https://github.com/laracasts/Laravel-5-Generators-Extended)

**Comment by pavoltanuska** [comment]
What about adding it as "require-dev" to base's composer.json?

**Comment by tabacitu** [comment]
That's an **excellent** idea. Thank you! 

We then just need to autoload it in BaseServiceProvider if the environment is not production, so that the developer doesn't have to worry about it.  So we save 2 installation steps, in one move. Nice! Pretty excited about this, thank you :-)

**Comment by tabacitu** [comment]
Also, I vote we require laracasts/generators in backpack/generators.

**Comment by OwenMelbz** [comment]
What does laracasts/generators get used for currently?

**Comment by tabacitu** [comment]
@OwenMelbz the db migration. It's the first command in the "[do it really fast](https://laravel-backpack.readme.io/v3.0/docs/crud-example#section-doing-it-all-very-fast)" process.

**Comment by tabacitu** [comment]
Fixed. Starting with Backpack\Base 0.7.9:
- backpack\base has a "require-dev" for backpack\generators;
- backpack\generators has a "require" for laracasts\generators;
- if the environment is "local", BaseServiceProvider autoloads both classes;

This can be easily changed down the line, if we decide there's a better option.

Cheers!

**Comment by tabacitu** [comment]
[keep writing here if you have comments/alternatives, please]

**Comment by tabacitu** [comment]
Ok. So. Sadly, this can't be done. The ```require-dev``` provision only works on the root composer.json, just like ```scripts```. It won't work for installed packages. Composer will just ignore their ```require-dev```.

I'd be very _very_ happy to find a way around this, but I've scoured the internet and found none.

So we need to manually install the generators. What I _have_ done to ease the pain a little bit is autoload the generators (both backpack and laracasts) in BaseServiceProvider if the classes exist. This turns the installation from a 2-step process to 1-step:
```php
composer require backpack/generators --dev
composer require laracasta/generators --dev
```
