### ISSUE TITLE
 MassAssignmentException in laravel CRUD operation

### ISSUE THREAD

**Issue by Prathamesh555** [Laravel-Backpack/Generators#45]
# Bug report
 MassAssignmentException
### What I did:
while updating the user status above error thrown.
### What I expected to happen:
status should be updated
### What happened:
 MassAssignmentException is thrown
### Backpack, Laravel, PHP, DB version:
Laravel 5.4,phpmyadmin

**Comment by Prathamesh555** [comment]
please help me to solve this(issue may be posted on github as its my first time)

**Comment by lloy0076** [comment]
How is this an error with the generator package? This sounds more like a StackOverflow question - and even if it's not it's in the wrong component.

Given you say you have Laravel 5.4 installed it seems this may be on an older version of the software.

Please re-open WITH more information (what version of backpack, maybe a full back trace and what you did to GET the error) in the right component.
