### ISSUE TITLE
Using BackPack with nwidart/laravel-modules

### ISSUE THREAD

**Issue by LarryTX** [Laravel-Backpack/Generators#48]
# Bug report

### What I did:
I am trying to set up a Web application that has a huge number of models in Laravel/BackPack. To simply dump all the models into \App would be total chaos. Making the transition from Yii2, the nwidart/Laravel-modules approach seemed to be the best approach since it would allow me to create as many modules as I needed, thus keeping the number of models in any given module down to a manageable number. Laravel-modules creates a directory named \Modules at the same level as \Modules then has subdirectories for each module, such as \Modules\Network. Each module then has subdirectories for Config, Console, Database, Entities, Http, Providers, Resources, Routes, and Tests, thus paralleling the structure of the main app. Each module is very much like a package in that it could easily be pulled out of one Laravel application and put into another with minimal effort.

Working from that starting point, I looked everyplace I could think of to find how to specify a path in the BackPack CRUD generator and couldn't come up with anything. I then tried issuing the following Artisan command:

    php artisan backpack:model \Modules\Network\NetworkDevice --softdelete

In this case, I already had a module, named Network created by Laravel-Modules. I was trying to create a model for the network_devices table.

### What I expected to happen:
I expected to have the model generator place a NetworkDevice model in the directory \Modules\Network directory with the namespace Modules\Network.
### What happened:
The model generator created a directory structure like this: \App\Modules\Network and put the NetworkDevice.php file in it with the namespace App\Modules\Network.
### What I've already tried to fix it:
Since I am unable to find any documentation on how to provide a modular organization in BackPack,I am at a loss on how to proceed.
### Backpack, Laravel, PHP, DB version:
BackPack: ver. 3.5
Laravel: ver. 5.7.20
PHP: ver. 7.2.10
DB: MariaDB ver. 10.1.36

I'm really hoping that BackPack will be able to handle complex Web applications. I really like what I've seen of it thus far, although I must say that I am totally dismayed at the inability of Laravel, in general, to handle master-detail forms, a totally ubiquitous part of any contemporary Web application. Surely, BackPack can handle something as normative as modularizing.

**Comment by LarryTX** [comment]
Sorry, I went with Yii2/Yii 3. Laravel is a bit too primitive for  me. Probably good for very simplistic websites (and probably overkill for that). I need something that can stand up to highly complex relationships with user interfaces that embody multiple one-to-many and many-to-many in one input and save action. Laravel just isn’t up to it.


Larry E. Lutz

**Comment by tabacitu** [comment]
Thanks for replying @LarryTX . 

I don't agree with you about Laravel vs Yii - I think Laravel's just fine for that, it has no restrictions on folder structure, just defaults/preferences. But yeah, it does require parting from its recommended folder structure. Then again I haven't tried Yii in 4-5 years - so what do I know? 😆 It might be much better than Laravel by now, could be.

Good luck with Yii - you're welcome back to Laravel any time you want :-)

Cheers!
