### ISSUE TITLE
Call parent::setup in stub

### ISSUE THREAD

**Issue by mserralta** [Laravel-Backpack/Generators#51]
I think parent::setup() could be called? 

I am using a third intemediate Controllet between final CrudController and BaseCrudController where I do some setup. Actually I am setting access array values according to spatie/permission package. 

https://github.com/Laravel-Backpack/Generators/blob/5b35eb7e16b205edbae0ec052592f4a6d4990f8f/src/Console/stubs/crud-controller.stub#L21

**Comment by tabacitu** [comment]
Hi @mserralta ,

Indeed - in your case it would be ```parent::store()```, not ```parent::storeCrud()```. 

But since most people don't have that third intemediate ```BaseCrudController```, for them only ```parent::storeCrud()``` would work.

Cheers!
