### ISSUE TITLE
Not getting the Calendar icon in the widget like in the Doc

### ISSUE THREAD

**Issue by FreddyCrugger** [Laravel-Backpack/Generators#60]
Hello,

Laravel 6
Backpack 4

On this page:
https://backpackforlaravel.com/docs/4.0/crud-fields#datetime

It shows a little calender icon in the field but it is not showing up when using the doc code as:

![1](https://user-images.githubusercontent.com/6231274/72472908-d8a5bb80-37e5-11ea-963e-4dec270bc199.png)

But this code from the doc:

```
        $this->crud->addField([
            'name' => 'published_at',
            'label' => 'Date',
            'type' => 'date_picker',
            'date_picker_options' => [
                'todayBtn' => 'linked',
                'format' => 'dd-mm-yyyy',
                'language' => 'en'
            ],
        ]);
```

Does not output the icon at all. Please see the pick after I add the code to my Controller

![1](https://user-images.githubusercontent.com/6231274/72473056-291d1900-37e6-11ea-9d03-35c47dab6d65.png)

Is it possible to update the correct code in the doc please?

Thank you.

**Comment by tabacitu** [comment]
Hi @FreddyCrugger ,

This is how it looks on my end
<img width="643" alt="date_picker" src="https://user-images.githubusercontent.com/1032474/72528310-6c719900-3873-11ea-887f-c84d6aaaad23.png">


when I do

```php

        $this->crud->addField([   // DateTime
            'name'  => 'datetime_picker',
            'label' => 'Datetime picker (jQuery plugin)',
            'type'  => 'datetime_picker',
            // optional:
            'datetime_picker_options' => [
                'format'   => 'DD/MM/YYYY HH:mm',
                'language' => 'en',
            ],
            // 'wrapperAttributes' => ['class' => 'col-md-6'],
            'tab' => 'Time and space',
        ]);
```

That's the expected result - without a calendar icon. 

Looks like the image in the docs is actually from the ```datetime_picker``` field (notice time too). I've replaced the image in the docs with the accurate one, without the calendar icon, thanks for raising this.

Cheers!
