### ISSUE TITLE
[4.1.0] undefined function Backpack\Generators\Console\Commands\str_plural()

### ISSUE THREAD

**Issue by mikiman2028** [Laravel-Backpack/Generators#66]
# Bug report

### What I did

fresh installation, first model creation:

php artisan backpack:crud objekt

### What I expected to happen

it should create model, controller and view files

### What happened

`Call to undefined function Backpack\Generators\Console\Commands\str_plural()

  at vendor/backpack/generators/src/Console/Commands/CrudControllerBackpackCommand.php:83
    79|      * @return string
    80|      */
    81|     protected function replaceNameStrings(&$stub, $name)
    82|     {
  > 83|         $table = str_plural(ltrim(strtolower(preg_replace('/[A-Z]/', '_$0', str_replace($this->getNamespace($name).'\\', '', $name))), '_'));
    84| 
    85|         $stub = str_replace('DummyTable', $table, $stub);
    86|         $stub = str_replace('dummy_class', strtolower(str_replace($this->getNamespace($name).'\\', '', $name)), $stub);
`
### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

all  latest, it's new project

When I run ```php artisan bac### PHP VERSION:
PHP 7.3.15-3+ubuntu19.10.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:24:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.15-3+ubuntu19.10.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.3.0@36d8958b5b8058ef0641806e490f91102fdea70d

### BACKPACK VERSION:
4.1.x-dev@02bf0a23ebfb81578604a0c89880f13468f1574a
kpack:version``` the output is:

**Comment by anovelexperience** [comment]
> We've removed `laravel/helpers` in 4.1, we should account for that in `backpack/generators` too. I'll move this issue there to make sure we fix it before launch - thanks again.

What is the best workaround while this gets fixed? Should we just install `laravel/helpers` for now?

TIA

**Comment by tabacitu** [comment]
Hi @anovelexperience . It's been fixed in #68 , but that will only get merged once 4.1 is launched. Until then please change your composer.json to require ```        "backpack/generators": "^3.0|4.1.x-dev as 3.0.0",``` - that should do it for you.

Closing the issue since it's fixed on that branch, which will get merged soon enough.

**Comment by anovelexperience** [comment]
Thanks @tabacitu. Will changing my composer cause me to lose any changes I've already made to crudcontollers or layout files (vendor/backpack…)? I'm struggling to understand the use of the pipe symbol here.

**Comment by tabacitu** [comment]
Depends on the one you're talking about:
- It will NOT affect any changes to ```resources/views/vendor/backpack/...```
- It will YES erase all changes to ```vendor/backpack/crud/src/resources/views/...```

The first one is the only good way to change blade files in Backpack.

Files in the ```vendor``` folder that's at the same level as your ```app``` folder should never be changed, because your changes will be lost upon ```composer update```. And will also be ignored by composer. Sorry if I'm dumbing it down too much - you might already know that, but many people ignore this so I felt like it needed to be said.

If you have any changes in the main vendor folder, you can just copy-paste the changed blade files in the corresponding folder in ```resources/views/vendor/backpack``` - Backpack checks there first for blade files, and loads it from there if it exists.

**Comment by anovelexperience** [comment]
That's what I imagined. I was wondering what the pipe symbol (|) meant in the composer configuration. I've never seen that before. TIA

**Comment by tabacitu** [comment]
Or - ```"^3.0|4.1.x-dev as 3.0.0"``` reads as ```^3.0``` or ```4.1.x-dev as 3.0.0```

**Comment by anovelexperience** [comment]
Right, ok. I understand the pipe is analogous to "or" but, does that mean use what's on the 3.0 branch unless there is a 4.1.x-dev branch, in which case use that? Don't worry about answering quickly… This is just for my personal learning. I could also read the documentation!

**Comment by tabacitu** [comment]
Well the 3.0 version doesn't exist yet. But it will once it's launched. So now it should fall back to the second option, the 4.1 branch. But once 3.0 is released it will use the official release.
