### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/Generators#67]
# Bug report
Using version ^2.0 for backpack/generators
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for backpack/generators ^2.0 -> satisfiable by backpack/generators[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, v2.0.7].
    - Can only install one of: backpack/crud[4.0.x-dev, 4.1.x-dev].
    - Can only install one of: backpack/crud[4.0.x-dev, 4.1.x-dev].
    - Can only install one of: backpack/crud[4.0.x-dev, 4.1.x-dev].
    - Conclusion: install backpack/crud 4.0.x-dev
    - Installation request for backpack/crud 4.1.x-dev -> satisfiable by backpack/crud[4.1.x-dev].

### What I did:
 composer require backpack/generators --dev

### What I expected to happen:
php artisan backpack:crud notification

### What happened:
uninstall this package to update the backpack to version 4.1, as it did not allow me
Now i want to reinstall and i can't

### PHP VERSION:
PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v6.18.3@4e48acfaba87f08320a2764d36c3b6a4a4112ccf

### BACKPACK VERSION:
4.1.x-dev@50e4bda7c80da16c69da0bc9ade0aa0e0f9408a3

my file composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "backpack/backupmanager": "^2.0.0",
        "backpack/crud": "4.1.x-dev",
        "backpack/permissionmanager": "^5.0",
        "backpack/settings": "^3.0.0",
        "barryvdh/laravel-elfinder": "^0.4.3",
        "cviebrock/eloquent-sluggable": "6.0.*",
        "eduardoarandah/backpacklogviewer": "^1.0",
        "fideloper/proxy": "^4.0",
        "intervention/image": "^2.3",
        "khsing/world": "^0.8.0",
        "lab404/laravel-auth-checker": "^1.6",
        "laravel/framework": "^6.0",
        "laravel/helpers": "^1.1",
        "laravel/tinker": "^2.0",
        "wildside/userstamps": "^1.1"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.3",
        "facade/ignition": "^1.16",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.5",
        "fzaninotto/faker": "^1.4",
        "laracasts/generators": "^2.0",
        "mockery/mockery": "^1.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```

**Comment by tabacitu** [comment]
Thanks for testing the beta @DanielKimmich ! At this point I recommend you do ```composer require backpack/crud:"4.1.x-dev as 4.0.99"``` (notice the 4.0.99 alias). None of the other Backpack packages have been updated to support 4.1.

https://backpackforlaravel.com/docs/4.1/installation
