### ISSUE TITLE
Command to create a new filter:

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#70]
```php artisan backpack:filter {name}```

**Comment by pxpm** [comment]
Just don't! Thanks @stale !

**Comment by tabacitu** [comment]
@karandatwani92 any chance you can take this on, too?

**Comment by karandatwani92** [comment]
Yes, noted. We will have it soon.

**Comment by karandatwani92** [comment]
@tabacitu  Please check #153
