### ISSUE TITLE
Command to create a new field:

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Generators#73]
```php artisan backpack:field {name}```

**Comment by pxpm** [comment]
bump

**Comment by tabacitu** [comment]
@karandatwani92 any chance you can take this on, too?

**Comment by karandatwani92** [comment]
Yes, noted. We will have it soon.

**Comment by karandatwani92** [comment]
I'm thinking of two types of action for ** field, column, filter,widget**:

* php artisan backpack:field {name}
for new plain file
* php artisan backpack:field {name} --backpack_field_name
 to copy view file with new name in case one wants modify and use if for own purpose as i did with webcam field?
 
 what do you say?

**Comment by tabacitu** [comment]
I love it. But let's name the second one:
```bash
php artisan backpack:field {name} --from={source_field_name}
```

That should be easier to read, right?

**Comment by tabacitu** [comment]
Now that I think about it... a new empty file doesn't really make sense at all... You'd have to code everything from scratch... so perhaps a good starting point would be the `text` field.

You specify no `--from` => it creates it from TEXT
You specify a `--from` => it creates it from whatever you chose

What do you think @karandatwani92 ?

**Comment by pxpm** [comment]
My two cents here:

`php artisan backpack:field {name} --from="any_field"`
- Copy the provided field. Nothing to see here.

`php artisan backpack:field {name}`
- Create the field file from a stub similar to the text input but without all the suffix, hint, prefix stuff ... if you want text, use --from="text"
```php
@include(wrapper_start)
<input type="text" />
@include(wrapper_end)
```
`php artisan backpack:field {name}--withAssets`
```php
@include(wrapper_start)
<input type="text" data-init-function="bpFieldInitMyFieldElement" />
@include(wrapper_end)

@push('crud_fields_styles')
  @loadOnce('your_field_name_field_style')
    <style>
        .your_field_class { display: none; }
    </style>
  @endLoadOnce
@endpush

@push('crud_fields_scripts')
  @loadOnce(asset('myFieldScript.js')

@loadOnce('bpFieldInitMyFieldElement')
    function bpFieldInitMyFieldElement(element) {
    // element is the jquery wrapped element where init function is defined. 
    }
@endLoadOnce

@endpush
```

Even the empty stubs show alot on how the Backpack fields are structured, for me, much more understandable than looking at current field implementations and figure out the "story" on why things are there. 

Cheers

**Comment by karandatwani92** [comment]
@tabacitu Please check. #144

**Comment by tabacitu** [comment]
Whoohooo! Let's move the conversation to https://github.com/Laravel-Backpack/Generators/pull/144 then 🎉 We're making progress!!!
