### ISSUE TITLE
CRUD syntax option in CLI (choose array or fluent)

### ISSUE THREAD

**Issue by Mamatlatomate** [Laravel-Backpack/Generators#89]
Hi @tabacitu 

I just start my day by creating new CRUD and I noticed a important change in my Controller : the fluent syntax.
It's very interesting but maybe an option for the fluent syntax might be great aswell ?

I explain my case :
My entire project is based on the classic syntax and to stay coherent it would be interesting to set the generator on fluent OR classic by default and add and option to get the Controller with the fluent syntax.

Example :
`php artisan backpack:crud <entity_name> --fluent`

It's currently not very impactful but when you switch from a controller to another that surprises a bit 😄 

Mamat

**Comment by eduardoarandah** [comment]
What's the fluent syntax? don't see it mentioned in https://laravel.com/docs/7.x/controllers

**Comment by AbbyJanke** [comment]
@eduardoarandah Wrong docs :P It's for Backpack:

https://backpackforlaravel.com/docs/4.1/crud-fluent-syntax

@Mamatlatomate The Generated one simply uses the new syntax by default however you still have the option to overwrite and change back to the old one.

**Comment by tabacitu** [comment]
Hmm you're right @Mamatlatomate - for existing projects it's probably best to keep using the non-fluent syntax, for consistency. No point in rewriting existing CrudControllers - there's no tangible benefit. So yes there should still be a command to generate non-fluent CrudControllers, I agree. I do want the fluent syntax to be the default for _new projects_, though - I think that's better for new users, and faster for experienced users too (who know the syntax and just want to add one attribute to one field, something like that).

So I think we're going to go with something like this:
```php
php artisan backpack:crud <entity_name> // fluent
php artisan backpack:crud <entity_name> --fluent // fluent
php artisan backpack:crud <entity_name> --syntax=fluent // fluent syntax

php artisan backpack:crud <entity_name> --array // array syntax
php artisan backpack:crud <entity_name> --classic // array syntax
php artisan backpack:crud <entity_name> --syntax=array // array syntax
```

One of the above. Or maybe... all of the above?! In any case, I'd rather keep the fluent syntax the default, is what I'm saying 😆 

I'll work on the generators quite a bit this next week, I'll make sure to also tackle this - thanks! Until then, either use version `3.0.*` of generators (which generates non-fluent controllers) or manually change `column()` to `addColumn()` like Abby said. 

In hindsight, I should have pushed [3.1.0](https://github.com/Laravel-Backpack/Generators/releases) as 4.0.0 - it is a breaking change, technically, even if only for generated code - it breaks consistency.

**Comment by Mamatlatomate** [comment]
Yes indeed fluent syntax is for the best and I got not problems in changing for the array syntax 👍
My point was just to propose an option to the command to easily switch from one syntax to another. Some projects are not profitable to upgrade and since the doc is in array syntax, the copy/paste for new users is maybe easier ? 🤔

**Comment by tabacitu** [comment]
Just talked to @promatik - we decided to NOT do this. It'd be better to just teach people about the new syntax (the fluent syntax), rather than make it easier to use the array syntax.

We won't REMOVE the array syntax... but we don't plan on even mentioning it in v6, when you'll get A LOT more benefits in using the fluent one, because you get autocomplete.
