### ISSUE TITLE
[Bug] Problem adding CrudTrait to existing Model

### ISSUE THREAD

**Issue by yabbou** [Laravel-Backpack/Generators#95]
# Bug report

### What I did

After building a draft.yml for the Customer model:
```
php artisan blueprint:build 
php artisan backpack:crud Customer
```

### What I expected to happen

I expected
(1) the CrudTrait to be added to the existing Model, and
(2) the setUpCreateOperation() and setUpListOperation() to be filled in.

### What happened

```
PS C:\Apps\xampp\htdocs\cofour-intern>  php artisan blueprint:build 
...
PS C:\Apps\xampp\htdocs\cofour-intern> php artisan backpack:crud Customer     
Controller created successfully.

   ErrorException 

  Undefined variable: position

  at C:\Apps\xampp\htdocs\cofour-intern\vendor\backpack\generators\src\Console\Commands\CrudModelBackpackCommand.php:94
    90|                     // the same as the array index - arrays start counting from 0,
    91|                     // IDEs start counting from 1
    92| 
    93|                     // add CrudTrait
  > 94|                     array_splice($file_array, $position, 0, '    use \\'.$this->crudTrait.';');
    95| 
    96|                     // save the file
    97|                     $this->files->put($path, implode(PHP_EOL, $file_array));
    98| 

  1   C:\Apps\xampp\htdocs\cofour-intern\vendor\backpack\generators\src\Console\Commands\CrudModelBackpackCommand.php:94
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined variable: position", "C:\Apps\xampp\htdocs\cofour-intern\vendor\backpack\generators\src\Console\Commands\CrudModelBackpackCommand.php")

  2   C:\Apps\xampp\htdocs\cofour-intern\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:33     
      Backpack\Generators\Console\Commands\CrudModelBackpackCommand::handle()
PS C:\Apps\xampp\htdocs\cofour-intern> 
```
### What I've already tried to fix it

I manually added `use Backpack\CRUD\app\Models\Traits\CrudTrait;` to the model, and `use CrudTrait;` to the class body, which auto-generated the proper files (expectation 1), but does not fill out the setUpOperations (expectation 2). 

Also described [here](https://stackoverflow.com/questions/62943908/problem-adding-crudtrait-to-existing-model) on Stackoverflow.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.7 (cli) (built: Jun  9 2020 13:36:15) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.19.0@67d6d9688122dcf6c449b74ddc873fc9934e81e6

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323 
```

**Comment by pxpm** [comment]
Hello @yabbou 

I just moved your issue from crud repository to generators, I think here is the correct place for it.

The error states that the controller already exists. Did you try deleting it and running the command again ?

Can you make sure you are using the last version of generators ? It's 3.1.3 atm.

Best,
Pedro

**Comment by yabbou** [comment]
composer.json: `Using version ^3.1 for backpack/generators`. Tried now to delete and re-run, but i was unsuccessful. 

I did manually build the migrations with the Eloquent syntax prior to running these commands. (Found out about the Blueprint method later...) Could having an already-working database table be problematic?

**Comment by yabbou** [comment]
I had also had given Product model details in the draft.yml, and when i deleted that controller, i get the following:

![image](https://user-images.githubusercontent.com/36824257/87999664-92e5ea80-cac9-11ea-9350-8830ce2f22a1.png)

**Comment by yabbou** [comment]
run the commands in the reverse order than showed in the intro videos:
```
php artisan backpack:crud Customer
php artisan blueprint:build 
```
and thank God it worked 😌

**Comment by yabbou** [comment]
Caveat actually: only the Customer models will be created without the error. Any `backpack:crud <Model>` commands run after  `php artisan blueprint:build` still return the error.

**Comment by pxpm** [comment]
Hello again @yabbou .

Maybe `php artisan blueprint:erase` before the build command?

**Comment by yabbou** [comment]
It seems that `php artisan blueprint:build` should be run only after all the Blueprint draft.yml models have been constructed. `php artisan blueprint:erase` indeed allows me to continue constructing the draft.yml. I guess I was just assuming that `blueprint:build` would be run _before_ `backpack:build`, as in the intro videos. But it does seem to work this way. 🙂

**Comment by yabbou** [comment]
Very strange.
```
php artisan blueprint:build 
php artisan backpack:crud <Model> 

php artisan blueprint:erase
#repeat
```
Something about the Controller having been created from the first command lets the rest be reset in the `build -> erase` cycle.

**Comment by yabbou** [comment]
Commenting out the automated adding of CrudTrait works. Presumably should not be necessary, but now the regular command call order works:

```
blueprint:build
backpack:build
```


**CrudModelBackpackCommand.php (line 75):**

```
            // if it does not have CrudTrait, add the trait on the Model

            $classDefinition = 'class '.$this->getNameInput().' extends';

            // foreach ($file_array as $key => $line) {
            //     if (Str::contains($line, $classDefinition)) {
            //         if (Str::endsWith($line, '{')) {
            //             // add the trait on the next
            //             $position = $key + 1;
            //         } elseif ($file_array[$key + 1] == '{') {
            //             // add the trait on the next next line
            //             $position = $key + 2;
            //         }

            //         // keep in mind that the line number shown in IDEs is not
            //         // the same as the array index - arrays start counting from 0,
            //         // IDEs start counting from 1

            //         // add CrudTrait
            //         array_splice($file_array, $position, 0, '    use \\'.$this->crudTrait.';');

            //         // save the file
            //         $this->files->put($path, implode(PHP_EOL, $file_array));

            //         // let the user know what we've done
            //         $this->info('Model already exists! We just added CrudTrait on it.');

            //         return false;
            //     }
            // }

            $this->error('Model already exists! Could not add CrudTrait - please add manually.');

            return false;
        }
```

I likely moved some file out of place, but I am not sure which one...

**Comment by yabbou** [comment]
Very strange as well... only for some models, the Controller's `setUpListOperation()` method receives auto-generated columns.

**Comment by yabbou** [comment]
All the new Controllers have included auto-filled `setUpListOperation()` and `setUpCreateOperation()` methods, thank God.

**Comment by wejdanAlahaideb** [comment]
I am having same issue, i have noticed that this happen if I manually deleted the file generated by **backpack:crud <model>** command

**Comment by pxpm** [comment]
Wouldn't #100 fix this ?

**Comment by promatik** [comment]
Hi @yabbou, I tried to generate a model with blueprint and then build backpack, and the model got correctly fixed with the `CrudTrait`. Do you still happen to have this problem?

**Comment by yabbou** [comment]
I ran a `php artisan backpack:install` as an attempt to update my version of Backpack, but I seem to still have the version from before the updates. If it works by you, that could very well be reliable, but how would you recommend updating and testing myself?

**Comment by promatik** [comment]
@yabbou you'll need to run

- `composer update backpack/crud` to update Backpack CRUD
- `composer update backpack/generators` to update Backpack Generators

Please give it a try and let us know the result 🙌

**Comment by tabacitu** [comment]
@promatik I also noticed [this problem](https://github.com/Laravel-Backpack/Generators/issues/95#issuecomment-665967884) this week. I generated a few models and the Generators didn't fill in the column & fields - so I think there's truly a bug here - and big one.

Do you mind investigating this please and create a PR if possible? If it doesn't fill in the fields&columns, this package only provides a minor boost in productivity so it's pretty big problem.

**Comment by promatik** [comment]
@tabacitu I've found the bug causing the problem reported by @yabbou https://github.com/Laravel-Backpack/Generators/issues/95#issuecomment-665967884, and I've just opened a PR for that https://github.com/Laravel-Backpack/Generators/pull/104.

I think this issue is no longer a problem, I'll close it for now.
Let's move the conversation to https://github.com/Laravel-Backpack/Generators/pull/104
