### ISSUE TITLE
Models in Top level directory recreated in model sub folder

### ISSUE THREAD

**Issue by bomshteyn** [Laravel-Backpack/Generators#97]
# Bug report

### What I did

`php artisan backpack:crud Product`

### What I expected to happen

I expected it to use the models from the top level directory 

### What happened

The crud command created a new Product model in the models directory and attached new controller to that empty model

### What I've already tried to fix it

I looked through the config file assuming that this is some sort of preset which can be changed to specify the location of the models, but didn't find such a setting. 

### Backpack, Laravel, PHP, DB version

PHP 7.4.8 (cli) (built: Jul  9 2020 23:43:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.25.0@fdf3d4a40447eb286ba3820768306cae64bcc0b3

### BACKPACK VERSION:
4.1.17@952ba942c7ff8b41fc2409d3c3cfef68dd48bf18

**Comment by tabacitu** [comment]
Indeed @bomshteyn - in Backpack during generation we assume the model is within `Models`. Which is _common_, but not intuitive at all. 

We should fix this - the most intuitive way would probably be to:
- pick up the Model in the top level if it exists
- pick up the Model in `Models` if top level doesn't exist
- ask the developer to choose between them if it exists in both places

I've tagged this, so it's on our to-do-list for this current version (4.1).
Thanks!

**Comment by shorton89** [comment]
@tabacitu Will it check to make sure the model uses CrudTrait?

If so, I may need to make sure all of my models that may eventually need that trait, have it.

**Comment by jamespavett** [comment]
Would it also be possible for it to check sub directories? As there is the same problem with them and name spacing as well.

**Comment by promatik** [comment]
Hi everyone!
I've just created a PR to solve this issue, thank you for reporting it @bomshteyn 🙌
Let's move the conversation there; #102
