### ISSUE TITLE
[Bug] crud building breaks at model creation on Windows OS

### ISSUE THREAD

**Issue by MiAlmeida** [Laravel-Backpack/Generators#98]
When running any of the following commands:

php artisan backpack:build
or
php artisan backpack:crud XYZ
or
php artisan backpack:crud-model XYZ

execution breaks with
Undefined offset: 1
  at [local_laravel_path]\vendor\backpack\generators\src\Console\Commands\CrudModelBackpackCommand.php:84

I'm running a fresh install with Laravel 7 + Backpack on Windows 10 x64 with Visual Studio Code
All latest versions.

It turns out CrudModelBackpackCommand.php on line 65 uses the infamous **explode** using **PHP_EOL** with known bad results on some Windows environments. Unfortunately mine included.

So replacing line 65:
            $file_array = explode(PHP_EOL, $file);
with:
            $file_array = preg_split('/\n|\r\n?/', $file);

resolves this issue.

**Comment by pxpm** [comment]
Hello @MiAlmeida 

I'v just moved your issue to the correct repository. Atm i'v not a win 10 machine available to test this, but I'm having one soon and hope I can dig into this.

I am just concerned that your fix did not cover all use cases for line breaking. I would go with something like: `/(\r\n)|\r|\n/`

Could you give it a try a let us know if it works for you ?

Best,
Pedro

**Comment by MiAlmeida** [comment]
Hi Pedro,
thanks for moving the issue. I'm very new to this... :)

Your regular expression works for me.

Best,
Miguel

**Comment by MiAlmeida** [comment]
As an extra note: some models I had made with blueprint went through the explode(PHP_EOL, $file) without any problem, but the ones I manually customized and saved in Visual Studio Code gave me the issue and using preg_split was my problem solver.
A quick Google search made it apparent the explode method using PHP_EOL has inconsistent results in Windows.

Cheers.

**Comment by pxpm** [comment]
The problem might be that, saving with VSC might change the line breaks and PHP_EOL would be configured to work let's say with linux line breaks, and your VSC saves them with Windows format.

I have nothing against using REGEX and I think in this scenario is the best option and cover all use cases for line breaks. 

I will ping @tabacitu so he can give his inputs. 

Best,
Pedro

**Comment by tabacitu** [comment]
Thanks guys! I had no idea that was a problem on Windows. I've created PR https://github.com/Laravel-Backpack/Generators/pull/100 with your collaborative solution. I've tested too and can confirm it's still working for me too, on Mac OS with Laravel Valet.

Please give it a last try and let me know if I should merge it. Let's move the conversation inside PR https://github.com/Laravel-Backpack/Generators/pull/100

Cheers!
