### ISSUE TITLE
[Bug] Call to undefined method App\User::identifiableAttribute()

### ISSUE THREAD

**Issue by MiAlmeida** [Laravel-Backpack/Generators#99]
I created an **AgentCrudController** with a **setupCreateOperation()** including fields with related entries.

The Agent class belongsTo the **App\User** class through the user_id and belongsTo the **App\Models\Country** class through the country_id

User class implements the **public function agent()** with **hasOne**
Country class implements the **public function agents()** with **hasMany**
Agent class implements both **public function user()** and **public function country()** with **belongsTo**

The code:

`protected function setupCreateOperation()
{
        CRUD::setValidation(JudgeRequest::class);

		/*$this->crud->addField(
            [
                'name' => 'user_id',
                'attribute' => 'name'
            ]
        );*/
        CRUD::field('user_id')->attribute('name');
        CRUD::field('country_id')->attribute('country');
...`

This gives me a **Call to undefined method App\User::identifiableAttribute()** error on proceeding to Add an Agent.

Tested workarounds:
1. Use the addField method as shown in the above code
2. Creating the identifiableAttribute() in the User model

I mention the Country relationship because that one works perfectly using fluent syntax without resorting to the addField() method.

Am I missing something in the fluent syntax?

Latest versions Laravel + Backpack + Windows 10 + VSC

**Comment by pxpm** [comment]
My guess is that your user model is not using crud trait.

**Comment by MiAlmeida** [comment]
Your guess is accurate. Indeed it isn't. I thought that was only necessary if I implemented a user CRUD through backpack which I don't.
Also I thought that using the fluent syntax was the same as using the attribute array.
Anyway... with the **use \Backpack\CRUD\app\Models\Traits\CrudTrait;** in the user model both methods work.

I'm new to the whole Laravel and Backpack scene. Sorry to bother.

**Comment by pxpm** [comment]
Don't need to be sorry. We all started without full knowledge. 

Take in mind that everything that needs backpack function needs the trait or the crud controller.

What I recommend is to use some alternative channels to clarify your issues. We use GitHub only for issues in the software or feature request, not for general questions. 

I will let the bot close this issue so you get the links to our other mediums. 

Wish you the best and good learning :)

Pedro
